from enum import IntEnum


class Vl53l5cxStatus(IntEnum):
    """VL53L5CX status codes"""

    NOT_UPDATED = 0
    SIGNAL_RATE_TOO_LOW_ON_SPAD = 1
    TARGET_PHASE = 2
    SIGMA_ESTIMATOR_TOO_HIGH = 3
    TARGET_CONSISTENCY_FAILED = 4
    RANGE_VALID = 5
    WRAP_AROUND_NOT_PERFORMED = 6
    RATE_CONSISTENCY_FAILED = 7
    SIGNAL_RATE_TOO_LOW_FOR_TARGET = 8
    RANGE_VALID_WITH_LARGE_PULSE = 9
    RANGE_VALID_NO_TARGET_DETECTED_AT_PREVIOUS_RANGE = 10
    MEASUREMENT_CONSISTENCY_FAILED = 11
    TARGET_BLURRED_BY_ANOTHER = 12
    TARGET_DETECTED_INCONSISTENT_DATA = 13
    NO_TARGET_DETECTED = 255
